functions/modules/codes.js, functions/modules/events.js, functions/modules/security.js
@arvee-init This PR is for your reference to see how appcheck (captcha-based device verification) is implemented server-side. See also how we rely on not just `context.app` but also captcha code in `functions/modules/codes.js:341-367`.
Closes #19.
Use an abstracted function to check for appcheck. The `context.app` value is synthesised by middleware. See [docs](https://firebase.google.com/docs/app-check/cloud-functions?authuser=0&hl=en).
OFF-CODE ACTIONS:
[x] Enforce cloud firestore appcheck
[x] Enforce storage appcheck
[x] Enforce appcheck in functions code
POST-MERGE:
@actuallymentor needs to edit the settings in the prod environment before merging changes to `main`.
=> ✨ lock down all functions that are public facing

cypress/integration/static-print-qr/1-view-and-claim.js, firestore.rules, functions/index.js, functions/modules/codes.js, functions/modules/health.js, functions/modules/helpers.js, functions/modules/poap_api.js, src/App.js, src/components/atoms/Input.js, src/components/atoms/Text.js, src/components/organisms/StaticClaim.js, src/hooks/printed_qrs.js, src/modules/firebase.js
=> ✨ working first version of static claimer

cypress/e2e/static-print-qr/1-view-and-claim.js
=> 🐛 fix failing test due to updates interface

functions/modules/codes.js, functions/modules/events.js
Added some breadcrumbs so we can find that weird -1 thing.
=> 🐛 tracking the -1 bug source as described by Ruben

functions/modules/codes.js
Guess this is an argument to use Typescript?
=> 🐛 force string type

functions/modules/events.js, public/locales/en/dynamic.json, src/App.js, src/components/atoms/Container.js, src/components/atoms/Style.js, src/components/organisms/EventCreate.js, src/components/organisms/StaticClaim.js, src/hooks/events.js, src/hooks/printed_qrs.js, src/modules/helpers.js
Allow for custom css for kiosks
=> ✨ custom css on the regular event types

functions/modules/events.js, functions/package-lock.json, public/locales/en/dynamic.json, src/components/atoms/Container.js, src/components/organisms/Claim.js, src/components/organisms/EventCreate.js, src/hooks/events.js, src/modules/firebase.js
Allows the user to make QR claim links in the kiosk to forward to `/static/claim` instead of `/claim`.
=> ✨ custom claim page tested to work locally

src/components/atoms/Container.js, src/components/molecules/Loading.js, src/components/organisms/StaticClaim.js, src/hooks/printed_qrs.js
Show generic black/white spinner if event meta is not loaded yet.
=> ✨ load non-poap generic styles for static drops

functions/modules/codes.js
=> 🐛 faulty destructuring instead of assignment

functions/index.js, functions/modules/health.js, functions/modules/static_qr_drop.js, public/locales/en/static.json, src/components/organisms/StaticClaimAdmin.js, src/modules/firebase.js
GDPR compliance tool as requested by Lucas and Sebastian.
=> ✨ option to delete all user data for static drops

functions/modules/events.js, functions/modules/helpers.js
Based on the slack message that caused confusion.
Result screenshot:
=> More explanatory message

src/components/organisms/Claim.js
Reverts poap-xyz/poap-qr-kiosk#95
=> Revert "Speed up feature reauest"

functions/modules/events.js
Add all POAP event data to the kiosk event.
=> Add the whole event to the data

functions/modules/codes.js, functions/modules/events.js, src/components/pages/EventCreate.jsx, src/modules/helpers.js
This should fix the counter updating issue that was blocking the release of features.
=> 🔥 hotfix: counter issue preventing main deployment

cypress/e2e/advanced-usage/1-view-and-claim-naive-and-custom.js, functions/modules/codes.js, src/components/molecules/CustomCssWrapper.jsx, src/components/pages/EventCreate.jsx, src/components/pages/EventView.jsx
=> ✨ Load custom css in iframe mode, add more tests for spec

functions/modules/codes.js, functions/modules/events.js, src/components/pages/EventCreate.jsx, src/modules/helpers.js
This releases the custom CSS in iframe feature. It also adds more robust automated testing for the iframe mode since it's used so much now.
=> Release of 26 sept

src/components/molecules/MethodCard.jsx
Base switch case for MethodCard
=> :art: MethodCard variation base

cypress/e2e/user-claimer/1-view-and-claim.js, src/components/pages/Claim.jsx, src/hooks/user_validation.js
Refactor the flow of user validation in the frontend.
=> Refactor validation logic

functions/modules/poap_api.js
This reverts commit 67e93171f49b95ba1827f04a3cf574606853523e.
=> Revert "Hotfix: Change url (#178)"

cypress/e2e/user-claimer/2-stress-test-claim.js, cypress/e2e/user-claimer/2-view-and-claim-w-game.js, functions/modules/claim.js, public/locales/en/translation.json, src/components/pages/EventAdmin.jsx, src/hooks/claim_codes.js
Redirect to the poap mint and extend expiration auth token to mint
=> Redirect to the poap mint and extend expiration auth token to mint

cypress/support/commands.js, index.html
* Removed from head
* Removed from cypress
=> chore(PLT2-255): remove matomo
